### ISSUE TITLE
Make all Articles of the month visible on the Homepage of the Magazine

### ISSUE THREAD

**Issue by woluweb** [joomla/magazine.joomla.org#1]
(this is a copy-paste of the suggestion made on the Glip channel)
just an open question : on the homepage https://magazine.joomla.org/ we only see a selection of the Articles of this month.
If I would not be an insider, I think I would never have searched for more Articles (no list in a side Module, no mention in the text): the only way to see it is to click on the little button at the bottom and then scroll down all the page to realize that there is more.
Also bc I am not sure people expect more than 9 Articles 😃
So maybe we should do something, like showing all Titles on the homepage or something

**Comment by Sandra97** [comment]
A possibility would be to have a module in the sidebar with the titles of the current edition.

**Comment by jeckodevelopment** [comment]
Done! Thank you for the suggestions!
