### ISSUE TITLE
Homepage magazine - Righ column: remove or place somewhere else the box 'My Account' 

### ISSUE THREAD

**Issue by mosselmania** [joomla/magazine.joomla.org#11]
Homepage magazine - Righ column: remove or place somewhere else the 'My Account' box.

'My account' is placed in the right top column. Its better placing this block lower or remove it altogether. It's  position is to prominent and confusing: do you need an account to see or even download the magazine? Why you have to login?

Maybe in general it is better to put the ´my account´ next to the Search field (with an icon).

**Comment by particthistle** [comment]
Thanks for the suggestion @mosselmania 

Raised it with JCM team this week while performing other modifications. Discussion under way.

**Comment by conconnl** [comment]
I move the module around and removed it from some pages.
