### ISSUE TITLE
Improve Readability on Detail Page (Part 2)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/magazine.joomla.org#16]
Before:
![grafik](https://user-images.githubusercontent.com/828371/99817466-41b83700-2b4d-11eb-8bc3-6937aacd3204.png)

After:
![grafik](https://user-images.githubusercontent.com/828371/99817395-25b49580-2b4d-11eb-9862-04eb892883b3.png)

.eb-entry-body.type-standard.clearfix {
    font-size: 18px;
    line-height: 140%;
    padding: 0 145px;
}

#eb h1 {
    color: #2E3657;
font-size:36px;
}

#eb h2, #eb h3, #eb h4, #eb h5, #eb h6 {
    margin: 50px 0 20px;
    color: #E94F34;
}

.eb-entry-meta.text-muted a {
    color: #EA7C55;
    text-decoration: underline !important;
}

.es-post-state {
    padding: 0 145px;
}

.eb-entry-head {
    padding: 20px 145px;
}

#eb .eb-reading-indicator {
    padding: 4px 8px;
    display: inline-block;
    background-color: #5883A5;
    color: #fff;
}

**Comment by conconnl** [comment]
@particthistle can you create a PR for the things the team agreed upon?
https://github.com/joomla/magazine.joomla.org/blob/master/www/templates/joomla/css/custom.css

**Comment by particthistle** [comment]
Some variations I'm proposing from what @coolcat-creations suggested.

- Base font size only changing to 16px not 18px.
- Padding on article dropped back to 100px from 145px proposed.
- .eb-entry-body .eb-image.eb-post-thumb set to restore the article lead image back to full width of the layout.
- Reading indicator button set to #1e88e5 to match other buttons on the page and 3px radius added.

If that's all suitable, I'll put it into PR shortly.

`.eb-entry-body {
font-size: 16px;
line-height: 140%;
padding: 0 100px;
}
.eb-entry-body .eb-image.eb-post-thumb {
	max-width: auto;
	margin: 0 -100px;
}

#eb h1 {
color: #2E3657;
font-size:36px;
}

#eb h2, #eb h3, #eb h4, #eb h5, #eb h6 {
margin: 50px 0 20px;
color: #E94F34;
}

.eb-entry-meta.text-muted a {
color: #EA7C55;
text-decoration: underline !important;
}

.es-post-state {
padding: 0 100px;
}

.eb-entry-head {
padding: 20px 100px;
}

#eb .eb-reading-indicator {
padding: 4px 8px;
display: inline-block;
background-color: #1e88e5;
color: #fff;
border-radius: 3px;
}`

![image](https://user-images.githubusercontent.com/5515866/113378806-a02ad700-93c3-11eb-876d-43f5ad41f678.png)

**Comment by particthistle** [comment]
Please add further comments now to #25.

**Comment by andreagentil** [comment]
Only thing: I don't like the red for titles/subtiltes.
