### ISSUE TITLE
[jcm] Blog or Articles

### ISSUE THREAD

**Issue by brianteeman** [joomla/magazine.joomla.org#18]
The magazine refers to articles in the about section but in other parts of the UI it talks about blogs and posts. I am assuming that these are the strings from easyblog and it would be great if one or other was updated so we only use on term for the same thing. Personally I prefer articles to blogs as this is a magazine with issues and not an irregularly updated blog

**Comment by brianteeman** [comment]
Closing as its obviously not going to get a response :(

**Comment by jeckodevelopment** [comment]
Hi Brian,
thanks for reporting.
We'll take care of that asap

**Comment by particthistle** [comment]
Language overrides for the magazine have now been uploaded, so you'll now find the terminology has changed from "blogs" and "posts" to "issues" and "articles" and other language consistent with it being a magazine site vs a blog.

If anyone finds any missed strings please raise another issue or create a PR to extend #26.
