### ISSUE TITLE
Add a standard image & description in sharing link specific month of Magazine

### ISSUE THREAD

**Issue by hvdmeer** [joomla/magazine.joomla.org#27]
When I want to share a specific issue of the Magazine, let's say March 2021, there is no standard Magazine image & description available in the preview:

![mag-empty](https://user-images.githubusercontent.com/7062995/114146112-7ddf0f00-9917-11eb-8c29-6dc4d94149ab.png)

```
<meta property="og:description" content="There is no description for this category." />
<meta property="og:title" content="March" />
<meta property="og:image" content="https://magazine.joomla.org/components/com_easyblog/assets/images/default_category.png" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://magazine.joomla.org/all-issues/categories/march-2021" />
<meta property="og:site_name" content="Joomla! Community Magazine™" />
```

Can this be fixed? I would prefer a standard Magazine image and not the standard Joomla template image.

**Comment by skpandey885** [comment]
Hey! I would really Like to work on this issue.

**Comment by Harsh-Porwal424** [comment]
Hey! Hans van der Meer
Can I work on this issue?

**Comment by conconnl** [comment]
@andreagentil I'm sure we have discussed this before.
If @Sandra97 can make an image to replace this one, then I can add it too the server.
https://magazine.joomla.org/components/com_easyblog/assets/images/default_category.png

@imarklee is there an option in the component to define the default category description?
Or should we make a language override....

**Comment by Sandra97** [comment]
![idex](https://user-images.githubusercontent.com/4682328/133029027-89ff04af-3faa-4178-aa31-95198f255500.png)
Hi @conconnl, there's already a dedicated JCM image set up,as well as title and description (for Twitter and Facebook). So it was just a temporary bug I presume

**Comment by conconnl** [comment]
Maybe twitter is fixed, but if you look at: https://magazine.joomla.org/all-issues/categories/august
The og:image and og:description are still empty.

**Comment by Sandra97** [comment]
Yep, fine on Twitter, not on Facebook, but all OG meta are there. Can be a cache issue?

**Comment by andreagentil** [comment]
The Facebook debugger says that the description for the category is missing:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmagazine.joomla.org%2Fall-issues%2Fcategories%2Faugust

But there is an image, https://magazine.joomla.org/components/com_easyblog/assets/images/default_category.png.

**Comment by Sandra97** [comment]
True. Easy to solve. 
Make a copy of the existing pic, rename it default_category.png and put it in the folder 
/components/com_easyblog/assets/images/

**Comment by Sandra97** [comment]
But there will still be no description, nor title.
Best would be to understand why this page doesn't take the same meta as the other pages. Something should not be correctly set up

**Comment by andreagentil** [comment]
I've added a description to the category and now it's there:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmagazine.joomla.org%2Fall-issues%2Fcategories%2Faugust

It's the same with other links like that one, this is from May:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmagazine.joomla.org%2Fall-issues%2Fcategories%2Fmay-2021

**Comment by andreagentil** [comment]
> True. Easy to solve.
> Make a copy of the existing pic, rename it default_category.png and put it in the folder
> /components/com_easyblog/assets/images/

@conconnl Please, can you add the image?

![default_category](https://user-images.githubusercontent.com/8660106/133099724-eaa3e894-cba1-4ae9-af36-8448ea3f2a68.png)

**Comment by conconnl** [comment]
@imarklee can we put this files somewhere in the template folder?
Else it will probably be updated on every release

**Comment by imarklee** [comment]
@conconnl currently it does not support overrides for the default avatar. Will modify this in the next release to allow that to happen.

**Comment by Sandra97** [comment]
@conconnl @imarklee Adding the image will solve 50% of the issue. The other 50% is that the OG title and description are empty. I presume there's a way to add them?

**Comment by conconnl** [comment]
Everything is solvable manually just by adding the information in the category. 
As you can see the title is March in this example, which is the Category name. Adding a image and a description in the category will solve it. 

For the image I wanted to make sure the default is also nice, in case it was forgotten in the category. 

If the process would be, copy previous category to create a new one. Then the image would always be filled and the description as well, where you maybe need to change the month.
@andreagentil can you shed your light?

**Comment by imarklee** [comment]
Yeah, if we add a title and description on the category, the opengraph and twitter cards data will be reflected accordingly.

The only part as pointed out by @conconnl is that there should be an option to override the default category picture (for categories without a picture)

**Comment by andreagentil** [comment]
> Everything is solvable manually just by adding the information in the category.
> As you can see the title is March in this example, which is the Category name. Adding a image and a description in the category will solve it.
> 
> For the image I wanted to make sure the default is also nice, in case it was forgotten in the category.
> 
> If the process would be, copy previous category to create a new one. Then the image would always be filled and the description as well, where you maybe need to change the month.
> @andreagentil can you shed your light?

No problem with adding the image manually, my question for @imarklee is where do we have to add it? Because I've tried adding the image with the description, with no change, https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmagazine.joomla.org%2Fall-issues%2Fcategories%2Fjuly-2021

![Screenshot from 2021-09-14 10-17-40](https://user-images.githubusercontent.com/8660106/133221887-d7973bb1-334e-422a-9eee-762304554abf.png)

**Comment by imarklee** [comment]
@andreagentil Are you trying to change the title and the image? All you need to do is to edit the category and upload a picture for the category. 

![category_avatar](https://user-images.githubusercontent.com/892204/133225689-ec729361-ecb4-43c6-84cb-ee861d2dc83b.jpg)

**Comment by andreagentil** [comment]
I don't have the option to change the avatar...and I'm superuser

![Screenshot from 2021-09-14 10-45-58](https://user-images.githubusercontent.com/8660106/133226213-42188665-863b-4e28-b773-bdb69b7b0b41.png)

**Comment by imarklee** [comment]
The category avatar input will only be visible if it is enabled, since it is disabled, this is why you don't get to change it.

At the mean time, you can enable category avatars under Settings > Layout and enable the option `Enable Category Avatar`.

Once that is done, edit the category again and you will be able to change the avatar.

**Comment by andreagentil** [comment]
Now we are talking. Thanks @imarklee !
@Sandra97 do we have a square image like this one, for Instagram maybe? where can I find it?

![Screenshot from 2021-09-14 11-00-59](https://user-images.githubusercontent.com/8660106/133228605-6dea27db-b113-40a3-912d-b88338509132.png)

**Comment by Sandra97** [comment]
@andreagentil Why do you need a square pic? It's not a correct size for Facebook and Twitter, and you can't share link on Insta

**Comment by andreagentil** [comment]
Because when you share this link, Facebook reads the category avatar: 

![image](https://user-images.githubusercontent.com/8660106/133233172-3ba434d1-fe88-4ce2-8da1-68a3703c2964.png)

**Comment by Sandra97** [comment]
When shared on a fan page, display is fine for me:
![2](https://user-images.githubusercontent.com/4682328/133234796-8ec6ac6b-f423-45b0-93ef-c006f917888a.png)

**Comment by andreagentil** [comment]
True, it looks fine if you share to a page, not to a profile.

![image](https://user-images.githubusercontent.com/8660106/133235219-138ed387-d924-4254-95f0-dc149c5f72c0.png)

**Comment by andreagentil** [comment]
We can use this image and close the issue.

**Comment by andreagentil** [comment]
Image and description added to all 2021 categories.
