### ISSUE TITLE
Magazine Articles Keywords Saving Issue

### ISSUE THREAD

**Issue by aboarken** [joomla/magazine.joomla.org#28]
We are not able to save the keywords of our articles submitted to Joomla Magazine May issue. Whenever we write the article keywords then we click on save the draft....all keywords disappear.

Could anyone fix this issue. Thanks in advance.

![Keywords Saving Issue](https://user-images.githubusercontent.com/18500882/115087003-0a8c5d00-9f16-11eb-91f6-62d25a459195.png)

**Comment by crommie** [comment]
Do we still use metakeywords? https://www.clickminded.com/meta-keywords/

**Comment by particthistle** [comment]
@aboarken tags on the Post tab are more important.
I agree @crommie - keywords aren't giving a value add.
@imarklee?
