### ISSUE TITLE
Disallow change by authors after publish

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/magazine.joomla.org#3]
When an article is approved and published, it should not be possible for the author to change it or to submit changes for approval.

**Comment by imarklee** [comment]
We will add a new ACL Rule in the next version of EasyBlog (5.4.3) to disallow user group from editing a published post.

**Comment by jeckodevelopment** [comment]
Thank you

**Comment by conconnl** [comment]
@imarklee how is it going with this?

**Comment by conconnl** [comment]
@imarklee was this added to the latest version?

**Comment by imarklee** [comment]
@conconnl sorry, missed this. This is already added in EasyBlog 5.4.3

**Comment by conconnl** [comment]
@imarklee no problem.
@jeckodevelopment you can configure it according to your needs, let us know if all is OK.
