### ISSUE TITLE
Reading Time Bar CSS Issue

### ISSUE THREAD

**Issue by aboarken** [joomla/magazine.joomla.org#30]
The ready bar located above each Joomla! Magazine article is showing a CSS issue on mobile versions only as shown in the attached picture.

![css issue](https://user-images.githubusercontent.com/18500882/118345857-116fb500-b540-11eb-920a-cd0ed5d03c40.jpg)

**Comment by particthistle** [comment]
Closing as PR #32 addresses and resolves issue.

**Comment by aboarken** [comment]
Thank you @particthistle
