### ISSUE TITLE
Authors' Articles CSS View List Issue

### ISSUE THREAD

**Issue by aboarken** [joomla/magazine.joomla.org#31]
The authors' articles are not shown correctly in the mobile version as shown in the attached pictures.

![186522390_170689768205247_7823404448889000670_n](https://user-images.githubusercontent.com/18500882/118448441-acac8a00-b6fa-11eb-9f0f-9b0f353c6ec8.jpg)
![186522390_310419070670867_1988955948044044373_n](https://user-images.githubusercontent.com/18500882/118448447-adddb700-b6fa-11eb-9039-3ddc6db2f302.jpg)
![186517093_158772579539984_7042479772632223991_n](https://user-images.githubusercontent.com/18500882/118448450-adddb700-b6fa-11eb-89f0-703e7ef30ddb.jpg)

**Comment by particthistle** [comment]
Closing as PR #32 addresses and resolves issue.

**Comment by aboarken** [comment]
Thank you @particthistle
