### ISSUE TITLE
Error on 'Article Submissions Guide' page

### ISSUE THREAD

**Issue by Justine-Ayebale** [joomla/magazine.joomla.org#36]
Dear Team, 
Please look into the error on this page; https://magazine.joomla.org/author-guides/item/71-Article-Submission-Guide. 
It is linked from here; https://magazine.joomla.org/all-issues/october-2013/raising-the-bar?highlight=WyJzdWJtaXR0aW5nIiwiYXJ0aWNsZSIsIidhcnRpY2xlJywiLCJhcnRpY2xlJyIsImFydGljbGUncyIsIidhcnRpY2xlJyJd

From this Same page there is a link "Please write for us!" and the linked page has an Error
https://magazine.joomla.org/join-joomla-magazine

Thank you all for the great work you are doing.
Justine.

**Comment by skpandey885** [comment]
Hey! can i work on this issue?

**Comment by Harsh-Porwal424** [comment]
Hey! Justine Ayebale,
may I work on this issue?

**Comment by conconnl** [comment]
@andreagentil @particthistle can you define the right redirect in the htaccess, so we can update the server?

**Comment by andreagentil** [comment]
@conconnl 
From https://magazine.joomla.org/author-guides/item/71-Article-Submission-Guide to https://magazine.joomla.org/faq

From https://magazine.joomla.org/join-joomla-magazine to https://magazine.joomla.org/about

**Comment by conconnl** [comment]
Fixed on server as well

**Comment by Justine-Ayebale** [comment]
Thank you Y'all
