### ISSUE TITLE
Did not receive activation message

### ISSUE THREAD

**Issue by KLW-skd** [joomla/magazine.joomla.org#39]
This afternoon I registered for the newsletter **https://magazine.joomla.org/magazine-newsletter-thank-you** but did not receive any activation e-mail. 
My e-mail address is kevinwalker2512@yahoo.com and the user is **b1ngeraskd**.
Could you please investigate and advise.
Kevin Walker

**Comment by particthistle** [comment]
@KLW-skd just checking if you've been receiving the magazine announcement emails on the 20th of each month?

Yahoo's renown for junking things it perhaps shouldn't, so if you've not been getting them, check out your trash.

If you are getting it, close the issue when you get back to looking at it.

I've not got access to the newsletter list so can't check you're on there, but if you saw the confirmation page you provided a link to, then you're on the list, as there's not an activation process for the newsletter sign up. (@jeckodevelopment can you check depending on what @KLW-skd replies with?)

**Comment by particthistle** [comment]
@KLW-skd I've just been following up on this with @jeckodevelopment.

* We can see you're subscribed to the newsletter & it shows you're confirmed.
* We can't see we've been sending you monthly magazine notifications
* It's not showing us that you've actually clicked or opened any of the newsletters (a sign that yahoo have either blocked the clicks, or that they've still put the newsletter in quarantine somehow)

If you can check deeper in your yahoo account that would be great.

At this time without further reply, this is being closed. If you need to follow up further @KLW-skd contact the magazine via magazine at community.joomla.org
