### ISSUE TITLE
Responsive Display - Load more button bug

### ISSUE THREAD

**Issue by Sandra97** [joomla/magazine.joomla.org#5]
- Browse the homepage from a smartphone
- Click on View all posts
- You are redirected to a page with the same articles, not all posts are displayd
- You have to click on "Load More"
- Load more doesn't work, nothing happens

Note: You expect to see all articles after having clicked on View all posts and not to have to click again on another button

**Comment by conconnl** [comment]
@imarklee it seems that infinite scroll and/or the load more buttons doesn't do anything on mobile.

**Comment by imarklee** [comment]
It looks like there is some js conflicts going on with the infinite scroller and jquery from joomla. Could be due to the version conflicts. 

Can you try to configure EasyBlog to use its own version of jQuery? It's in the settings under Settings > General > System

**Comment by jeckodevelopment** [comment]
@imarklee thanks for the hint.

@Sandra97 done, can you please check if it works?

**Comment by Sandra97** [comment]
The 'load more' still doesn't work for me. 
(And I think that when you click on View All posts you expect to see all posts of the current edition, instead of all posts).

**Comment by imarklee** [comment]
@Sandra97 Thanks! Can you revert the settings and let me run more tests locally.

**Comment by imarklee** [comment]
Can you guys give it a try now? @conconnl applied a patch on the site and the infinite scroller should work fine.

**Comment by Sandra97** [comment]
@imarklee It works fine now on my phone. When I click on View all posts, I can now actually view all posts. Thanks!

**Comment by imarklee** [comment]
Thanks @Sandra97 @jeckodevelopment and @conconnl ! Can we close this?

**Comment by Sandra97** [comment]
Yes, I'm closing it as it works as expected.
It can always be re-opened if needed.
