### ISSUE TITLE
Newsletter Images

### ISSUE THREAD

**Issue by Sandra97** [joomla/magazine.joomla.org#7]
Image for the Subscription page:
![jcm-newsletter](https://user-images.githubusercontent.com/4682328/80058750-6e11c380-852a-11ea-92f1-668d8fcf55d3.jpg)

Image for the Thank you page:
![newsletter-thankyou](https://user-images.githubusercontent.com/4682328/80058752-736f0e00-852a-11ea-9c72-f0f5f0d27191.jpg)

**Comment by conconnl** [comment]
@Sandra97 
As discussed.
Subscribe page: https://magazine.joomla.org/magazine-newsletter
Thank you page: https://magazine.joomla.org/magazine-newsletter-thank-you
Archive page: https://magazine.joomla.org/magazine-newsletter-archive

**Comment by Sandra97** [comment]
Thanks Wilco. We're good.

I'm closing this issue.
