### ISSUE TITLE
Error 404 - Read our Previous Newsletters

### ISSUE THREAD

**Issue by aboarken** [joomla/magazine.joomla.org#8]
The user after his/her subscription to the newsletter, if he/she clicks on "Read our Previous Newsletters" button an error 404 will come up.

https://magazine.joomla.org/magazine-newsletter-archive

![Read our Previous Newsletters](https://user-images.githubusercontent.com/18500882/83064004-c0825a80-a069-11ea-8716-407505604b46.png)

Who is managing redirection plugin? Is Sh404SEF being using in Joomla! sites, this extension will make it easier to manage all 404 error and redirections.

**Comment by conconnl** [comment]
Fixed

**Comment by aboarken** [comment]
Thanks @conconnl 

Wilco nothing is visible on that page. Is it normal?
